services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  spring_app:
    image: ghizlanera/spring-boot-app:latest 
    container_name: spring-boot-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
